/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.deviceconnect.android.manager;

public final class R {
    public static final class array {
        public static final int authorization_attrib_list=0x7f060000;
        public static final int authorization_interface_list=0x7f060001;
        public static final int battery_attrib_list=0x7f060002;
        public static final int battery_interface_list=0x7f060003;
        public static final int camera_attrib_list=0x7f060004;
        public static final int camera_interface_list=0x7f060005;
        public static final int connect_attrib_list=0x7f060006;
        public static final int connect_interface_list=0x7f060007;
        public static final int dconnect_profile_list=0x7f060008;
        public static final int deviceorientation_attrib_list=0x7f060009;
        public static final int deviceorientation_interface_list=0x7f06000a;
        public static final int dice_attrib_list=0x7f06000b;
        public static final int dice_interface_list=0x7f06000c;
        public static final int drive_controller_attrib_list=0x7f06000d;
        public static final int drive_controller_interface_list=0x7f06000e;
        public static final int file_attrib_list=0x7f06000f;
        public static final int file_descriptor_attrib_list=0x7f060010;
        public static final int file_descriptor_interface_list=0x7f060011;
        public static final int file_interface_list=0x7f060012;
        /**  <item>非マルチパート</item> 
 <item>非マルチパート</item> 
         */
        public static final int http_methods=0x7f060013;
        public static final int light_attrib_list=0x7f060014;
        public static final int light_interface_list=0x7f060015;
        public static final int media_player_attrib_list=0x7f060016;
        public static final int media_player_interface_list=0x7f060017;
        public static final int mediastream_recording_attrib_list=0x7f060018;
        public static final int mediastream_recording_interface_list=0x7f060019;
        public static final int mhealth_attrib_list=0x7f06001a;
        public static final int mhealth_interface_list=0x7f06001b;
        public static final int notification_attrib_list=0x7f06001c;
        public static final int notification_interface_list=0x7f06001d;
        public static final int phone_attrib_list=0x7f06001e;
        public static final int phone_interface_list=0x7f06001f;
        public static final int proximity_attrib_list=0x7f060020;
        public static final int proximity_interface_list=0x7f060021;
        public static final int remote_controller_attrib_list=0x7f060022;
        public static final int remote_controller_interface_list=0x7f060023;
        public static final int servicediscovery_attrib_list=0x7f060024;
        public static final int servicediscovery_interface_list=0x7f060025;
        public static final int serviceinformation_attrib_list=0x7f060026;
        public static final int serviceinformation_interface_list=0x7f060027;
        public static final int settings_attrib_list=0x7f060028;
        public static final int settings_interface_list=0x7f060029;
        public static final int sphero_attrib_list=0x7f06002a;
        public static final int sphero_interface_list=0x7f06002b;
        public static final int string_empty=0x7f06002c;
        public static final int system_attrib_list=0x7f06002d;
        public static final int system_interface_list=0x7f06002e;
        public static final int temperature_attrib_list=0x7f06002f;
        public static final int temperature_interface_list=0x7f060030;
        public static final int vibration_attrib_list=0x7f060031;
        public static final int vibration_interface_list=0x7f060032;
        public static final int whitelist_menu_origin=0x7f060033;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int access_token_item_title_back_color=0x7f070000;
        public static final int access_token_item_title_color=0x7f070001;
        public static final int background=0x7f070002;
        public static final int guidance_background=0x7f070003;
        public static final int half_transparent=0x7f070004;
        public static final int text_color=0x7f070005;
    }
    public static final class dimen {
        public static final int access_token_inner_margin=0x7f080000;
        public static final int access_token_item_height=0x7f080001;
        public static final int access_token_item_title_margin=0x7f080002;
        public static final int access_token_item_width=0x7f080003;
        public static final int access_token_list_item_space=0x7f080004;
        public static final int access_token_listitem_margin=0x7f080005;
        public static final int activity_horizontal_margin=0x7f080006;
        public static final int activity_vertical_margin=0x7f080007;
        public static final int confirm_auth_application_item_margin=0x7f080008;
        public static final int confirm_auth_application_marksize=0x7f080009;
        public static final int confirm_auth_approval_button_height=0x7f08000a;
        public static final int confirm_auth_approval_button_width=0x7f08000b;
        public static final int confirm_auth_expireperiod_margin=0x7f08000c;
        public static final int confirm_auth_inner_margin=0x7f08000d;
        public static final int confirm_auth_linespace1_margin=0x7f08000e;
        public static final int confirm_auth_linespace2_margin=0x7f08000f;
        public static final int confirm_auth_listitem_itemmargin=0x7f080010;
        public static final int confirm_auth_listitem_margin=0x7f080011;
        public static final int confirm_auth_listitem_marksize=0x7f080012;
        public static final int confirm_auth_outline_margin_lr=0x7f080013;
        public static final int confirm_auth_outline_margin_tb=0x7f080014;
        public static final int item_deviceplugin_margin=0x7f080015;
    }
    public static final class drawable {
        public static final int access_token_delete_button=0x7f020000;
        public static final int button_blue=0x7f020001;
        public static final int button_blue_border=0x7f020002;
        public static final int card_item_bg=0x7f020003;
        public static final int close_icon=0x7f020004;
        public static final int close_icon_push=0x7f020005;
        public static final int confirm_auth_approval_button=0x7f020006;
        public static final int ic_action_labels=0x7f020007;
        public static final int ic_launcher=0x7f020008;
        public static final int icon=0x7f020009;
    }
    public static final class id {
        public static final int action_access_token=0x7f0c0042;
        public static final int action_search=0x7f0c0041;
        public static final int action_session_key=0x7f0c0043;
        public static final int action_settings=0x7f0c0044;
        public static final int activity_settings_category_fragment=0x7f0c0010;
        public static final int alert_icon=0x7f0c001c;
        public static final int alert_message=0x7f0c001d;
        public static final int bottomButton=0x7f0c0024;
        public static final int buttonApproval=0x7f0c0026;
        public static final int buttonDelete=0x7f0c000a;
        public static final int buttonOk=0x7f0c0002;
        public static final int buttonReject=0x7f0c0025;
        public static final int button_delete_origin=0x7f0c003f;
        public static final int button_manager_launcher_cancel=0x7f0c000e;
        public static final int button_manager_launcher_launch_or_stop=0x7f0c000f;
        public static final int container=0x7f0c000c;
        public static final int dconnect_launcher_menu_item_settings=0x7f0c0040;
        public static final int devicelist_icon=0x7f0c0037;
        public static final int devicelist_package_name=0x7f0c0038;
        public static final int devicelist_version=0x7f0c0039;
        public static final int dialog_origin_manual_entry_edit_origin=0x7f0c002c;
        public static final int dialog_origin_manual_entry_edit_title=0x7f0c002a;
        public static final int dialog_origin_manual_entry_text_origin=0x7f0c002b;
        public static final int dialog_origin_manual_entry_text_title=0x7f0c0029;
        public static final int disable_observer=0x7f0c001f;
        public static final int imageView=0x7f0c0004;
        public static final int imageView1=0x7f0c001a;
        public static final int imageViewApplicationIcon=0x7f0c0022;
        public static final int imageViewIcon=0x7f0c0009;
        public static final int image_app_icon=0x7f0c003a;
        public static final int isUrl=0x7f0c0017;
        public static final int linearLayoutFrame=0x7f0c0020;
        public static final int listView=0x7f0c0007;
        public static final int listViewScope=0x7f0c0003;
        public static final int listViewScopes=0x7f0c0027;
        public static final int listview_pluginlist=0x7f0c0034;
        public static final int listview_whitelist=0x7f0c0036;
        public static final int message=0x7f0c001e;
        public static final int noTokenView=0x7f0c0008;
        public static final int plugin_delete_btn=0x7f0c0031;
        public static final int plugin_icon=0x7f0c002d;
        public static final int plugin_package_name=0x7f0c002e;
        public static final int plugin_restart_btn=0x7f0c0030;
        public static final int plugin_settings_btn=0x7f0c0032;
        public static final int plugin_support_profiles=0x7f0c0033;
        public static final int plugin_version=0x7f0c002f;
        public static final int reqAttribute=0x7f0c0015;
        public static final int reqDeviceid=0x7f0c0016;
        public static final int reqInterfaces=0x7f0c0014;
        public static final int reqMethod=0x7f0c0012;
        public static final int reqPath=0x7f0c0018;
        public static final int reqProfile=0x7f0c0013;
        public static final int reqResList=0x7f0c001b;
        public static final int reqSend=0x7f0c0019;
        public static final int reqWesocket=0x7f0c0011;
        public static final int textView=0x7f0c0005;
        public static final int textViewAccessToken=0x7f0c000b;
        public static final int textViewApplicationName=0x7f0c0000;
        public static final int textViewExpirePeriod=0x7f0c0006;
        public static final int textViewGuidance=0x7f0c0023;
        public static final int textViewScope=0x7f0c0028;
        public static final int text_app_orgin=0x7f0c003c;
        public static final int text_app_title=0x7f0c003b;
        public static final int text_manager_launcher_message=0x7f0c000d;
        public static final int text_origin=0x7f0c003e;
        public static final int text_origin_title=0x7f0c003d;
        public static final int tokenHeader=0x7f0c0001;
        public static final int topApplicationInfo=0x7f0c0021;
        public static final int view_no_origin=0x7f0c0035;
    }
    public static final class layout {
        public static final int access_token_item_fragment=0x7f030000;
        public static final int access_token_item_scope=0x7f030001;
        public static final int access_token_list_fragment=0x7f030002;
        public static final int access_token_list_item=0x7f030003;
        public static final int activity_confirm_auth=0x7f030004;
        public static final int activity_dconnect_launcher=0x7f030005;
        public static final int activity_dconnect_settings=0x7f030006;
        public static final int activity_debug_main=0x7f030007;
        public static final int activity_warning_dialog=0x7f030008;
        public static final int confirm_auth_activity=0x7f030009;
        public static final int confirm_auth_scopes_list_item=0x7f03000a;
        public static final int dialog_origin_manual_entry=0x7f03000b;
        public static final int fragment_deviceplugin_info=0x7f03000c;
        public static final int fragment_devicepluginlist=0x7f03000d;
        public static final int fragment_privacypolicy=0x7f03000e;
        public static final int fragment_whitelist=0x7f03000f;
        public static final int item_deviceplugin_list=0x7f030010;
        public static final int item_known_applications=0x7f030011;
        public static final int item_open_source_licenses=0x7f030012;
        public static final int item_request_response_list=0x7f030013;
        public static final int item_whitelist_origin=0x7f030014;
    }
    public static final class menu {
        public static final int activity_dconnect_launcher=0x7f0b0000;
        public static final int activity_debug_main=0x7f0b0001;
        public static final int main=0x7f0b0002;
    }
    public static final class raw {
        public static final int andorid_support_v4=0x7f050000;
        public static final int android_support_v4_preferencefragment=0x7f050001;
        public static final int apache_mime4j=0x7f050002;
        public static final int java_websocket=0x7f050003;
        public static final int privacypolicy=0x7f050004;
        public static final int termsofservice=0x7f050005;
    }
    public static final class string {
        public static final int access_authority=0x7f090000;
        public static final int access_token=0x7f090001;
        public static final int access_token_delete_all_title=0x7f090002;
        public static final int access_token_delete_guidance=0x7f090003;
        public static final int access_token_delete_negative=0x7f090004;
        public static final int access_token_delete_positive=0x7f090005;
        public static final int access_token_delete_title=0x7f090006;
        public static final int access_token_list_item_format=0x7f090007;
        public static final int action_access_token=0x7f090008;
        public static final int action_input_session_key=0x7f090009;
        public static final int action_menu=0x7f09000a;
        public static final int action_search=0x7f09000b;
        public static final int action_settings=0x7f09000c;
        public static final int activity_deviceplugin_info_open_settings=0x7f09000d;
        public static final int activity_deviceplugin_info_profile=0x7f09000e;
        public static final int activity_deviceplugin_info_restart=0x7f09000f;
        public static final int activity_deviceplugin_info_settings=0x7f090010;
        public static final int activity_deviceplugin_info_title=0x7f090011;
        public static final int activity_deviceplugin_info_uninstall=0x7f090012;
        public static final int activity_deviceplugin_info_version=0x7f090013;
        public static final int activity_devicepluginlist_title=0x7f090014;
        public static final int activity_devicepluginlist_version=0x7f090015;
        public static final int activity_keyword=0x7f090016;
        public static final int activity_keyword_ok=0x7f090017;
        public static final int activity_launch_button_cancel=0x7f090018;
        public static final int activity_launch_button_launch=0x7f090019;
        public static final int activity_launch_button_settings=0x7f09001a;
        public static final int activity_launch_button_stop=0x7f09001b;
        public static final int activity_launch_message_launch=0x7f09001c;
        public static final int activity_launch_message_stop=0x7f09001d;
        public static final int activity_settings_about=0x7f09001e;
        public static final int activity_settings_allow_external_ip=0x7f09001f;
        public static final int activity_settings_app_infomation_summary=0x7f090020;
        public static final int activity_settings_close=0x7f090021;
        public static final int activity_settings_dconn_disabled=0x7f090022;
        public static final int activity_settings_dconn_enabled=0x7f090023;
        public static final int activity_settings_dconnect_disabled=0x7f090024;
        public static final int activity_settings_dconnect_enabled=0x7f090025;
        public static final int activity_settings_default_host=0x7f090026;
        public static final int activity_settings_default_keyword=0x7f090027;
        public static final int activity_settings_default_port=0x7f090028;
        public static final int activity_settings_device_plugin=0x7f090029;
        public static final int activity_settings_general=0x7f09002a;
        public static final int activity_settings_host=0x7f09002b;
        public static final int activity_settings_keyword=0x7f09002c;
        public static final int activity_settings_list_access_token_list=0x7f09002d;
        public static final int activity_settings_list_device_plugin=0x7f09002e;
        public static final int activity_settings_local_oauth=0x7f09002f;
        public static final int activity_settings_local_oauth_summary=0x7f090030;
        public static final int activity_settings_manage_whitelist=0x7f090031;
        public static final int activity_settings_no=0x7f090032;
        public static final int activity_settings_not_logged_in=0x7f090033;
        public static final int activity_settings_observer=0x7f090034;
        public static final int activity_settings_observer_summary=0x7f090035;
        public static final int activity_settings_open_source_licenses=0x7f090036;
        public static final int activity_settings_open_source_licenses_summary=0x7f090037;
        public static final int activity_settings_port=0x7f090038;
        public static final int activity_settings_privacy_policy=0x7f090039;
        public static final int activity_settings_require_origin=0x7f09003a;
        public static final int activity_settings_require_origin_summary=0x7f09003b;
        public static final int activity_settings_restart_device_plugin=0x7f09003c;
        public static final int activity_settings_restart_device_plugin_message=0x7f09003d;
        public static final int activity_settings_restart_device_plugin_title=0x7f09003e;
        public static final int activity_settings_security=0x7f09003f;
        public static final int activity_settings_server_keyword=0x7f090040;
        public static final int activity_settings_server_on_off=0x7f090041;
        public static final int activity_settings_server_settings=0x7f090042;
        public static final int activity_settings_ssl=0x7f090043;
        public static final int activity_settings_terms_of_service=0x7f090044;
        public static final int activity_settings_warning=0x7f090045;
        public static final int activity_settings_warning_require_origin_disabled=0x7f090046;
        public static final int activity_settings_warning_require_origin_enabled=0x7f090047;
        public static final int activity_settings_whitelist=0x7f090048;
        public static final int activity_settings_whitelist_enable=0x7f090049;
        public static final int activity_settings_whitelist_enable_summary=0x7f09004a;
        public static final int activity_settings_yes=0x7f09004b;
        public static final int activity_warning=0x7f09004c;
        public static final int activity_warning_disable=0x7f09004d;
        public static final int activity_warning_mess=0x7f09004e;
        public static final int activity_warning_ok=0x7f09004f;
        public static final int activity_whitelist_title=0x7f090050;
        public static final int app_name=0x7f090051;
        public static final int approval=0x7f090052;
        public static final int attribute=0x7f090053;
        public static final int authorization_profile=0x7f090054;
        public static final int battery_profile=0x7f090055;
        public static final int camera_profile=0x7f090056;
        public static final int cancel=0x7f090057;
        public static final int chrome_bookmark_provider_url=0x7f090058;
        public static final int connect_recording_profile=0x7f090059;
        public static final int content_description=0x7f09005a;
        public static final int contents=0x7f09005b;
        public static final int delete=0x7f09005c;
        public static final int delete_all=0x7f09005d;
        public static final int description=0x7f09005e;
        public static final int deviceorientation_profile=0x7f09005f;
        public static final int dialog_add_origin_negative=0x7f090060;
        public static final int dialog_add_origin_positive=0x7f090061;
        public static final int dialog_add_origin_title=0x7f090062;
        public static final int dialog_delete_origin_message=0x7f090063;
        public static final int dialog_delete_origin_negative=0x7f090064;
        public static final int dialog_delete_origin_positive=0x7f090065;
        public static final int dialog_origin_manual_entry_item_origin=0x7f090066;
        public static final int dialog_origin_manual_entry_item_title=0x7f090067;
        public static final int dialog_origin_manual_entry_message=0x7f090068;
        public static final int dialog_update_origin_negative=0x7f090069;
        public static final int dialog_update_origin_positive=0x7f09006a;
        public static final int dialog_update_origin_title=0x7f09006b;
        public static final int dice_profile=0x7f09006c;
        public static final int discovery=0x7f09006d;
        public static final int display_scope_authorization=0x7f09006e;
        public static final int display_scope_battery=0x7f09006f;
        public static final int display_scope_connect=0x7f090070;
        public static final int display_scope_deviceorientation=0x7f090071;
        public static final int display_scope_file=0x7f090072;
        public static final int display_scope_file_descriptor=0x7f090073;
        public static final int display_scope_mediastream_recording=0x7f090074;
        public static final int display_scope_mediastreams_play=0x7f090075;
        public static final int display_scope_notification=0x7f090076;
        public static final int display_scope_phone=0x7f090077;
        public static final int display_scope_proximity=0x7f090078;
        public static final int display_scope_servicediscovery=0x7f090079;
        public static final int display_scope_settings=0x7f09007a;
        public static final int display_scope_system=0x7f09007b;
        public static final int display_scope_vibration=0x7f09007c;
        public static final int drive_controller_profile=0x7f09007d;
        public static final int expire_period_date_format=0x7f09007e;
        public static final int expire_period_format=0x7f09007f;
        public static final int file_descriptor_profile=0x7f090080;
        public static final int file_profile=0x7f090081;
        public static final int guidance_comfirm=0x7f090082;
        public static final int http_method=0x7f090083;
        public static final int image_description=0x7f090084;
        public static final int interfaces=0x7f090085;
        public static final int key_settings_about_appinfo=0x7f090086;
        public static final int key_settings_about_privacypolicy=0x7f090087;
        public static final int key_settings_about_tos=0x7f090088;
        public static final int key_settings_dconn_allow_external_ip=0x7f090089;
        public static final int key_settings_dconn_host=0x7f09008a;
        public static final int key_settings_dconn_keyword=0x7f09008b;
        public static final int key_settings_dconn_local_oauth=0x7f09008c;
        public static final int key_settings_dconn_observation_interval=0x7f09008d;
        public static final int key_settings_dconn_observer_on_off=0x7f09008e;
        public static final int key_settings_dconn_port=0x7f09008f;
        public static final int key_settings_dconn_require_origin=0x7f090090;
        public static final int key_settings_dconn_server_on_off=0x7f090091;
        public static final int key_settings_dconn_ssl=0x7f090092;
        public static final int key_settings_dconn_whitelist=0x7f090093;
        public static final int key_settings_dconn_whitelist_origin_blocking=0x7f090094;
        public static final int key_settings_list_access_token=0x7f090095;
        public static final int key_settings_list_device_plugin=0x7f090096;
        public static final int key_settings_open_source_licenses=0x7f090097;
        public static final int key_settings_restart_device_plugin=0x7f090098;
        public static final int light_profile=0x7f090099;
        public static final int media_player_profile=0x7f09009a;
        public static final int mediastream_recording_profile=0x7f09009b;
        public static final int menu_add_origin=0x7f09009c;
        public static final int mhealth_profile=0x7f09009d;
        public static final int no_application_name=0x7f09009e;
        public static final int no_origin=0x7f09009f;
        public static final int no_token=0x7f0900a0;
        public static final int notapproval=0x7f0900a1;
        public static final int notification_profile=0x7f0900a2;
        public static final int ok=0x7f0900a3;
        public static final int password=0x7f0900a4;
        public static final int phone_profile=0x7f0900a5;
        public static final int profile=0x7f0900a6;
        public static final int proximity_profile=0x7f0900a7;
        public static final int remote_controller_profile=0x7f0900a8;
        public static final int select_or_url=0x7f0900a9;
        public static final int send_request=0x7f0900aa;
        public static final int servicediscovery_profile=0x7f0900ab;
        public static final int serviceid=0x7f0900ac;
        public static final int serviceinformation_profile=0x7f0900ad;
        public static final int settings_profile=0x7f0900ae;
        public static final int sphero_profile=0x7f0900af;
        public static final int system_profile=0x7f0900b0;
        public static final int temperature_profile=0x7f0900b1;
        public static final int url_hint1=0x7f0900b2;
        public static final int url_hint2=0x7f0900b3;
        public static final int userid=0x7f0900b4;
        public static final int vibration_profile=0x7f0900b5;
        public static final int websocket_close=0x7f0900b6;
        public static final int websocket_open=0x7f0900b7;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
 API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f0a0000;
        /**  All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f0a0001;
        public static final int AppTheme_Translucent=0x7f0a0002;
        public static final int access_token_delete_btn=0x7f0a0003;
    }
    public static final class xml {
        public static final int filelocation=0x7f040000;
        public static final int settings=0x7f040001;
    }
}
